// src/components/chapters/ChapterManager.vue
<template>
  <div>
    <div class="row form-group">
      <div class="col-5 text-left">
        <book-selector />
      </div>
      <div class="col text-left">
        <add-chapter v-show="hasBook && inAddMode" />
        <edit-chapter v-show="hasBook && inEditMode" />
      </div>
    </div>
    <chapter-table v-if="hasBook" />
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

import Book from '@/models/Book';
import Chapter from '@/models/Chapter';

import IState from '@/state/IState';
import { Store } from 'vuex';
import MutationTypes from '@/state/MutationTypes';
import { mixins } from 'vue-class-component';
import AddChapter from '@/components/chapters/AddChapter.vue';
import EditChapter from '@/components/chapters/EditChapter.vue';
import BookSelector from '@/components/books/BookSelector.vue';
import ChapterTable from '@/components/chapters/ChapterTable.vue';
import StoreMixin from '@/mixins/StoreMixin';

@Component({
  components: {
    AddChapter,
    BookSelector,
    ChapterTable,
    EditChapter,
  },
})
export default class ChapterManager extends mixins(StoreMixin) {
  get hasBook(): boolean {
    return this.store.state.bookSelected !== undefined;
  }

  get inAddMode(): boolean {
    return this.store.state.chapterEdited === undefined;
  }

  get inEditMode(): boolean {
    return !this.inAddMode;
  }
}
</script>

<style scoped>
</style>

// Angular/src/app/components/chapters/chapter-manager/chapter-manager.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Store } from '@ngrx/store';
import { map } from 'rxjs/operators';
import { Observable } from 'rxjs';
import { AppState } from '../../../state/app-state';
import { selectBookSelected, selectChapterEdited } from '../../../state/app.selectors';
import { AddChapter } from '../add-chapter/add-chapter';
import { EditChapter } from '../edit-chapter/edit-chapter';
import { BookSelector } from '../../books/book-selector/book-selector';
import { ChapterTable } from '../chapter-table/chapter-table';

@Component({
  selector: 'app-chapter-manager',
  imports: [CommonModule, AddChapter, EditChapter, BookSelector, ChapterTable],
  templateUrl: './chapter-manager.html',
  styleUrl: './chapter-manager.css',
})
export class ChapterManager {
  readonly hasBook$!: Observable<boolean>;
  readonly inAddMode$!: Observable<boolean>;
  readonly inEditMode$!: Observable<boolean>;

  constructor(private store: Store<{ app: AppState }>) {
    this.hasBook$ = this.store.select(selectBookSelected).pipe(map((book) => !!book));
    this.inAddMode$ = this.store.select(selectChapterEdited).pipe(map((chapter) => !chapter));
    this.inEditMode$ = this.store.select(selectChapterEdited).pipe(map((chapter) => !!chapter));
  }
}
