// question-trainer-ng/src/app/components/layout/tabs/tabs.component.ts
import { Component, OnInit, ContentChildren, QueryList, AfterContentInit, Input } from '@angular/core';
import { TabPageComponent } from '../tab-page/tab-page.component';

@Component({
  selector: 'app-tabs',
  templateUrl: './tabs.component.html',
  styleUrls: ['./tabs.component.css']
})
export class TabsComponent implements AfterContentInit {

  @ContentChildren(TabPageComponent) tabPageQueryList: QueryList<TabPageComponent>;

  tabPages: Array<TabPageComponent>;

  constructor() { }

  ngAfterContentInit(): void {
    this.tabPages = this.tabPageQueryList.toArray();
    if (this.tabPages.length > 0 && this.tabPages.every(tabPage => !tabPage.active)) {
      this.tabPages[0].active = true;
    }
  }

  setActiveTab(tabPageIndex: number) {
    this.tabPages.forEach(tabPage => tabPage.active = false);
    this.tabPages[tabPageIndex].active = true;
  }
}

<div>
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li *ngFor="let tabPage of tabPages; index as tabPageIndex" class="nav-item">
      <a
        class="nav-link"
        [class.active]="tabPage.active"
        data-toggle="tab"
        [href]="'#'+ tabPage.id"
        role="tab"
        (click)="setActiveTab(tabPageIndex)"
      ><h5>{{ tabPage.title }}</h5></a>
    </li>
  </ul>
  <div class="tab-content">
    <ng-content></ng-content>
  </div>
</div>

// Vue/src/components/Tabs.vue
<template>
  <div>
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li v-for="tabPage in tabPages" class="nav-item" v-bind:key="tabPage.id">
        <a
          :class="['nav-link', {active: tabPage.active}]"
          data-toggle="tab"
          :href="'#'+ tabPage.id"
          role="tab"
          :aria-controls="tabPage.title"
        ><h5>{{ tabPage.title }}</h5></a>
      </li>
    </ul>
    <div class="tab-content">
      <slot>
        <tab-page title="Default tab page">Add tab pages by using 'tab-page' components.</tab-page>
      </slot>
    </div>
  </div>
</template>

<script lang="ts">
import _ from 'lodash';
import uuid from 'uuid/v1';
import Vue from 'vue';
import { Component, Prop } from 'vue-property-decorator';

import TabPage from '@/components/TabPage.vue';

@Component
export default class Tabs extends Vue {
  private tabPages: TabPage[] = [];

  private mounted(): void {
    const tabPages = this.getTabPages();
    this.setActiveTabPage(tabPages);
    this.tabPages = tabPages;
  }

  private getTabPages(): TabPage[] {
    let tabPages: TabPage[];

    if (this.$slots.default === undefined) {
      tabPages = new Array<TabPage>();

      tabPages.push(new TabPage({
        propsData: {
          title: 'Default tab page',
        },
      }));

      return tabPages;
    }

    // @ts-ignore
    tabPages = this.$slots.default
      .map((vnode) => vnode.componentInstance)
      // @ts-ignore
      .filter((cmp) => !!cmp && cmp.$vnode.componentOptions.tag === 'tab-page');
    return tabPages;
  }

  private hasActiveTabPage(tabPages: TabPage[]): boolean {
    return _.findIndex(tabPages, (tabPage) => {
      return tabPage.active === true;
    }) !== -1;
  }

  private setActiveTabPage(tabPages: TabPage[]): void {
    if (tabPages.length === 0) { return; }

    if (this.hasActiveTabPage(tabPages)) {
      return;
    }

    for (let i = 0; i < tabPages.length; i++) {
      tabPages[i].active = (i === 0);
    }
  }
}
</script>
