// src/components/Tabs.vue
<template>
  <div>
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li v-for="title in titles" class="nav-item" v-bind:key="title">
        <a
          :class="['nav-link', {active: title === activeTitle}]"
          data-toggle="tab"
          :href="'#'+ title.split(' ').join('')"
          role="tab"
          :aria-controls="title"
        >{{ title }}</a>
      </li>
    </ul>
    <div class="tab-content">
      <slot>Add components or HTML to the slot of the tab component.</slot>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import { Component, Prop } from 'vue-property-decorator';

import TabPage from '@/components/TabPage.vue';

@Component
export default class Tabs extends Vue {
  private data(): any {
    return {
      activeTitle: undefined,
      titles: new Array<string>(),
    };
  }

  private created(): void {
    const childComponents = this.$slots.default;
    if (childComponents === undefined) { return; }
    for (const child of childComponents) {
      if (child.componentOptions === undefined) { continue; }
      const componentType = child.componentOptions.tag;
      if (componentType === 'tab-page') {
        // @ts-ignore
        const title = child.componentOptions.propsData.title;
        if (this.$data.titles.length === 0) {
          this.$data.activeTitle = title;
        }
        this.$data.titles.push(title);
      }
    }
  }
}
</script>

// question-trainer-ng/src/app/components/layout/tabs/tabs.component.ts
import { Component, OnInit, ContentChildren, QueryList, AfterContentInit, Input } from '@angular/core';
import { TabPageComponent } from '../tab-page/tab-page.component';

@Component({
  selector: 'app-tabs',
  templateUrl: './tabs.component.html',
  styleUrls: ['./tabs.component.css']
})
export class TabsComponent implements AfterContentInit {

  @ContentChildren(TabPageComponent) tabPageQueryList: QueryList<TabPageComponent>;

  tabPages: Array<TabPageComponent>;

  constructor() { }

  ngAfterContentInit(): void {
    this.tabPages = this.tabPageQueryList.toArray();
    if (this.tabPages.length > 0 && this.tabPages.every(tabPage => !tabPage.active)) {
      this.tabPages[0].active = true;
    }
  }

  setActiveTab(tabPageIndex: number) {
    this.tabPages.forEach(tabPage => tabPage.active = false);
    this.tabPages[tabPageIndex].active = true;
  }
}

<div>
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li *ngFor="let tabPage of tabPages; index as tabPageIndex" class="nav-item">
      <a
        class="nav-link"
        [class.active]="tabPage.active"
        data-toggle="tab"
        [href]="'#'+ tabPage.id"
        role="tab"
        (click)="setActiveTab(tabPageIndex)"
      ><h5>{{ tabPage.title }}</h5></a>
    </li>
  </ul>
  <div class="tab-content">
    <ng-content></ng-content>
  </div>
</div>
