// src/components/chapters/ChapterRecord.vue
<template>
  <tr>
    <td class="text-center" style="width: 70px;">
      <add-or-remove
        remove-color="red"
        @add="addQuestionsToList"
        @remove="removeQuestionsFromList"
      />
    </td>
    <td class="text-right" aria-label="Chapter number" style="width: 70px;">{{ chapter.nr }}</td>
    <td class="text-left" aria-label="Title of chapter">{{ chapter.title }}</td>
    <td
      class="text-center"
      style="width: 120px;"
      aria-label="Number of questions in this chapter"
    >{{ nrOfQuestions }}</td>
    <td class="text-center">
      <icon-button
        icon="edit"
        label="Edit chapter"
        :argument="chapter"
        @click="edit"
        :disabled="chapterInEditMode"
      />
      <icon-button
        icon="trash-alt"
        label="Trash chapter"
        @click="trash"
        :argument="chapter"
        :disabled="chapterInEditMode"
      />
    </td>
  </tr>
</template>

<script lang="ts">
import _ from 'lodash';
import { Component, Prop, Vue, Watch } from 'vue-property-decorator';
import AddOrRemove from '@/components/AddOrRemove.vue';
import bus from '@/MessageBus';
import Chapter from '@/models/Chapter';
import IconButton from '@/components/IconButton.vue';
import { mixins } from 'vue-class-component';
import MutationTypes from '@/state/MutationTypes';
import QuestionModalArgs from '@/types/QuestionModalArgs';
import StoreMixin from '@/mixins/StoreMixin';

@Component({
  components: {
    AddOrRemove,
    IconButton,
  },
})
export default class ChapterRecord extends mixins(StoreMixin) {
  @Prop() public chapter!: Chapter;

  get chapterInEditMode(): boolean {
    if (this.store.state.chapterEdited === undefined) { return false; }
    return this.store.state.chapterEdited.id === this.chapter.id;
  }

  get nrOfQuestions() {
    if (this.chapter.questions === undefined) { return 0; }
    return this.chapter.questions.length;
  }

  private trash(chapter: Chapter) {
    const args = new QuestionModalArgs(
      'Delete chapter',
      'Are you sure you want to delete this chapter?',
      this.trashConfirmed,
      'Yes',
      'No',
    );
    bus.showQuestionModal(args);
  }

  private trashConfirmed(): void {
    this.removeQuestionsFromList();
    this.store.commit(MutationTypes.Chapter.removeChapterById, this.chapter.id);
  }

  private edit(chapter: Chapter): void {
    this.store.commit(MutationTypes.Chapter.setEditedChapter, chapter);
  }

  private addQuestionsToList(): void {
    _.forEach(this.chapter.questions, (q) => {
      this.store.commit(MutationTypes.QuestionList.addToList, q);
    });
  }

  private removeQuestionsFromList(): void {
    _.forEach(this.chapter.questions, (q) => {
      this.store.commit(MutationTypes.QuestionList.removeFromList, q);
    });
  }
}
</script>

<style scoped>
.btn-group-xs > .btn,
.btn-xs {
  padding: 0.25rem 0.4rem;
  font-size: 0.875rem;
  line-height: 0.5;
  border-radius: 0.2rem;
}
</style>

// Angular/src/app/components/chapters/chapter-record/chapter-record.ts
import { Component, DestroyRef, Input, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Store } from '@ngrx/store';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import _ from 'lodash';
import { Chapter } from '../../../models/chapter';
import { AppState } from '../../../state/app-state';
import { addToQuestionList, removeChapterById, removeFromQuestionList, setEditedChapter } from '../../../state/app.actions';
import { selectChapterEdited } from '../../../state/app.selectors';
import { AddOrRemove } from '../../add-or-remove/add-or-remove';
import { IconButtonComponent } from '../../icon-button/icon-button';
import { MessageBusService } from '../../../services/message-bus.service';
import { QuestionModalArgs } from '../../../types/question-modal-args';

@Component({
  selector: 'tr[app-chapter-record]',
  imports: [CommonModule, AddOrRemove, IconButtonComponent],
  templateUrl: './chapter-record.html',
  styleUrl: './chapter-record.css',
})
export class ChapterRecord implements OnInit {
  private readonly store = inject<Store<{ app: AppState }>>(Store);
  private readonly bus = inject(MessageBusService);
  private readonly destroyRef = inject(DestroyRef);
  @Input({ required: true }) chapter!: Chapter;

  chapterInEditMode = false;

  ngOnInit(): void {
    this.store
      .select(selectChapterEdited)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((edited) => {
        this.chapterInEditMode = !!edited && edited.id === this.chapter.id;
      });
  }

  get nrOfQuestions(): number {
    if (!this.chapter.questions) {
      return 0;
    }
    return this.chapter.questions.length;
  }

  trash(chapter: Chapter): void {
    const args = new QuestionModalArgs(
      'Delete chapter',
      'Are you sure you want to delete this chapter?',
      () => this.trashConfirmed(),
      'Yes',
      'No'
    );
    this.bus.showQuestionModal(args);
  }

  private trashConfirmed(): void {
    this.removeQuestionsFromList();
    this.store.dispatch(removeChapterById({ chapterId: this.chapter.id }));
  }

  edit(chapter: Chapter): void {
    this.store.dispatch(setEditedChapter({ chapter }));
  }

  addQuestionsToList(): void {
    _.forEach(this.chapter.questions, (q) => {
      this.store.dispatch(addToQuestionList({ question: q }));
    });
  }

  removeQuestionsFromList(): void {
    _.forEach(this.chapter.questions, (q) => {
      this.store.dispatch(removeFromQuestionList({ question: q }));
    });
  }
}
