// Angular/src/app/components/library/memory-usage/memory-usage.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-memory-usage',
  imports: [CommonModule],
  templateUrl: './memory-usage.html',
  styleUrl: './memory-usage.css',
})
export class MemoryUsage implements OnInit {
  id = 'memory-usage-2487234';
  usageInBytes = 0;
  maxStorageInBytes = 5 * 1024 * 1024;

  usagePercentage(): number {
    const onePercent = this.maxStorageInBytes / 100;
    return this.usageInBytes / onePercent;
  }

  ngOnInit(): void {
    let lsTotal = 0;
    for (const key in localStorage) {
      if (!Object.prototype.hasOwnProperty.call(localStorage, key)) {
        continue;
      }
      const xLen = (localStorage[key].length + key.length) * 2;
      lsTotal += xLen;
    }
    this.usageInBytes = lsTotal;
  }
}

// src/components/library/MemoryUsage.vue
<template>
  <div>
    <div class="row">
      <div class="col-2">
        <label for="id" class="font-weight-bold">Memory Usage:</label>
      </div>
      <div class="col-11 text-left">
        <progress :value="usageInBytes" :max="maxStorageInBytes"></progress>
      </div>
    </div>
    <div class="row">
      <div class="col">
        {{usagePercentage().toFixed(2)}}%
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
export default class MemoryUsage extends Vue {
  private id: string = 'memory-usage-2487234';
  private usageInBytes: number = 0;
  private maxStorageInBytes: number = 5 * 1024 * 1024;

  private usagePercentage(): number {
    var onePercent = this.maxStorageInBytes / 100;
    return this.usageInBytes / onePercent;
  }

  private mounted(): void {
    let lsTotal: number = 0;
    let xLen: number = 0;
    let x: any;
    for (x in localStorage) { 
      if (!localStorage.hasOwnProperty(x))
      {
        continue;
      } 
      xLen = ((localStorage[x].length + x.length) * 2);
      lsTotal += xLen; 
    }
    this.usageInBytes = lsTotal;
  }
}
</script>

<style scoped>
</style>
