// Angular/src/app/components/books/add-book/add-book.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import _ from 'lodash';

@Component({
  selector: 'app-add-book',
  imports: [CommonModule, FormsModule],
  templateUrl: './add-book.html',
  styleUrl: './add-book.css',
})
export class AddBook {
  @Input() errMessage = '';
  @Output() add = new EventEmitter<string>();
  @Output() titleChanged = new EventEmitter<{ old: string; new: string }>();

  buttonText = 'Add';
  bookTitle = '';
  errorMessage = '';
  private previousTitle = '';

  get invalidTitle(): boolean {
    if (_.isEmpty(this.bookTitle)) {
      return true;
    }
    return !_.isEmpty(this.errMessage);
  }

  get bookTitleIsEmpty(): boolean {
    return _.isEmpty(this.bookTitle);
  }

  get errorMessageToShow(): string {
    if (_.isEmpty(this.bookTitle)) {
      return '';
    }
    return this.errorMessage;
  }

  ok(): void {
    if (this.invalidTitle) {
      return;
    }
    const bookTitle = this.bookTitle;
    if (_.isEmpty(bookTitle)) {
      return;
    }
    this.add.emit(bookTitle);
    this.bookTitle = '';
    this.previousTitle = '';
  }

  cancel(): void {
    this.bookTitle = '';
    this.previousTitle = '';
  }

  onTitleChanged(newTitle: string): void {
    this.titleChanged.emit({ old: this.previousTitle, new: newTitle });
    this.previousTitle = newTitle;
  }

  ngOnChanges(): void {
    this.errorMessage = this.errMessage;
  }
}

// src/components/books/AddBook.vue
<script lang="ts">
import _ from 'lodash';
import { Component, Prop, Vue, Watch } from 'vue-property-decorator';
import BookBase from '@/components/books/BookBase.vue';

@Component
export default class AddBook extends BookBase {
  @Prop() public errMessage!: string;

  protected buttonText: string = 'Add';

  get invalidTitle(): boolean {
    if (_.isEmpty(this.bookTitle)) { return false; }
    return !_.isEmpty(this.errMessage);
  }

  protected ok(): void {
    if (this.invalidTitle) { return; }
    const bookTitle = this.bookTitle;
    if (_.isEmpty(bookTitle)) { return; }
    this.$emit('add', bookTitle);
    this.bookTitle = '';
  }

  protected cancel(): void {
    this.bookTitle = '';
  }

  @Watch('bookTitle')
  private onBookTitleChanged(newTitle: string, oldTitle: string) {
    this.$emit('title-changed', { old: oldTitle, new: newTitle });
  }

  get errorMessageToShow(): string {
    if (_.isEmpty(this.bookTitle)) { return ''; }
    return this.errMessage;
  }
}
</script>
