// src/components/chapters/EditChapter.vue
<script lang="ts">
import _ from 'lodash';
import { Component, Prop, Vue, Watch } from 'vue-property-decorator';
import uuid from 'uuid/v1';
import Chapter from '@/models/Chapter';
import IState from '@/state/IState';
import MutationTypes from '@/state/MutationTypes';
import ChapterBase from '@/components/chapters/ChapterBase.vue';

@Component
export default class EditChapter extends ChapterBase {
  protected buttonText: string = 'Edit';

  get chapters(): Chapter[] {
    if (this.store.state.bookSelected === undefined) { return []; }
    return this.store.state.bookSelected.chapters;
  }

  get canExecute() {
    return !this.hasError
      && !_.isEmpty(this.chapter.nr)
      && !_.isEmpty(this.chapter.title)
      && !this.chapterNumberExists()
      && !this.titleExists();
  }

  get hasError() {
    return !_.isEmpty(this.error.title) || !_.isEmpty(this.error.nr);
  }

  @Watch('store.state.chapterEdited')
  private onChapterEdited() {
    const chapterEdited = this.store.state.chapterEdited;
    if (chapterEdited === undefined) { return; }
    this.chapter.id = chapterEdited.id;
    this.chapter.nr = chapterEdited.nr;
    this.chapter.title = chapterEdited.title;
  }

  @Watch('chapters')
  private chaptersChanged(): void {
    this.numberChanged();
    this.titleChanged();
  }

  private ok(): void {
    if (!this.canExecute) { return; }

    this.store.commit(MutationTypes.editChapter, this.chapter);

    this.cancel();
  }

  private chapterNumberExists(): boolean {
    return _.findIndex(this.chapters, (chapter) => {
      return chapter.nr.toLowerCase() === this.chapter.nr.toLowerCase() && chapter.id !== this.chapter.id;
    }) !== -1;
  }

  private numberChanged(): void {
    if (this.chapterNumberExists()) {
      this.error.nr = 'Chapter already exists for this book.';
      return;
    }

    this.error.nr = '';
  }

  private titleExists(): boolean {
    return _.findIndex(this.chapters, (chapter) => {
      return chapter.title.toLowerCase() === this.chapter.title.toLowerCase() && chapter.id !== this.chapter.id;;
    }) !== -1;
  }

  private titleChanged(): void {
    if (this.titleExists()) {
      this.error.title = 'Title already exists for this book.';
      return;
    }

    this.error.title = '';
  }

  private cancel(): void {
    this.resetData();
    this.store.commit(MutationTypes.setEditedChapter, undefined);
  }
}
</script>

// Angular/src/app/components/chapters/edit-chapter/edit-chapter.ts
import { Component, DestroyRef, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Store } from '@ngrx/store';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import _ from 'lodash';
import { Chapter } from '../../../models/chapter';
import { AppState } from '../../../state/app-state';
import { editChapter, setEditedChapter } from '../../../state/app.actions';
import { selectBookSelected, selectChapterEdited } from '../../../state/app.selectors';

@Component({
  selector: 'app-edit-chapter',
  imports: [CommonModule, FormsModule],
  templateUrl: './edit-chapter.html',
  styleUrl: './edit-chapter.css',
})
export class EditChapter implements OnInit {
  private readonly store = inject<Store<{ app: AppState }>>(Store);
  private readonly destroyRef = inject(DestroyRef);
  buttonText = 'Edit';
  chapter = { id: '', nr: '', title: '' };
  error = { nr: '', title: '' };
  chapters: Chapter[] = [];



  ngOnInit(): void {
    this.store
      .select(selectBookSelected)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((book) => {
        this.chapters = book?.chapters ?? [];
        this.numberChanged();
        this.titleChanged();
      });

    this.store
      .select(selectChapterEdited)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((chapterEdited) => {
        if (!chapterEdited) {
          return;
        }
        this.chapter.id = chapterEdited.id;
        this.chapter.nr = chapterEdited.nr;
        this.chapter.title = chapterEdited.title;
        this.numberChanged();
        this.titleChanged();
      });
  }

  get canExecute(): boolean {
    return (
      !this.hasError &&
      !_.isEmpty(this.chapter.nr) &&
      !_.isEmpty(this.chapter.title) &&
      !this.chapterNumberExists() &&
      !this.titleExists()
    );
  }

  get hasError(): boolean {
    return !_.isEmpty(this.error.title) || !_.isEmpty(this.error.nr);
  }

  chapterNumberExists(): boolean {
    return (
      _.findIndex(
        this.chapters,
        (chapter) =>
          chapter.nr.toLowerCase() === this.chapter.nr.toLowerCase() &&
          chapter.id !== this.chapter.id
      ) !== -1
    );
  }

  titleExists(): boolean {
    return (
      _.findIndex(
        this.chapters,
        (chapter) =>
          chapter.title.toLowerCase() === this.chapter.title.toLowerCase() &&
          chapter.id !== this.chapter.id
      ) !== -1
    );
  }

  resetError(): void {
    this.chapter.nr = '';
    this.chapter.title = '';
  }

  resetChapter(): void {
    this.error.nr = '';
    this.error.title = '';
  }

  resetData(): void {
    this.resetChapter();
    this.resetError();
  }

  numberChanged(): void {
    if (this.chapterNumberExists()) {
      this.error.nr = 'Chapter number already exists for this book.';
      return;
    }
    this.error.nr = '';
  }

  titleChanged(): void {
    if (this.titleExists()) {
      this.error.title = 'Title already exists for this book.';
      return;
    }
    this.error.title = '';
  }

  ok(): void {
    if (!this.canExecute) {
      return;
    }

    this.store.dispatch(editChapter({ nr: this.chapter.nr, title: this.chapter.title }));
    this.cancel();
  }

  cancel(): void {
    this.resetData();
    this.store.dispatch(setEditedChapter({ chapter: undefined }));
  }
}
