// src/components/questionList/QuestionListRecord.vue
<template>
  <tr>
    <td><icon-button icon="minus" color="red" label="Remove from question list" :argument="question" @click="removeFromQuestionList"/></td>
    <td aria-label="Question number">{{ index }}</td>
    <td aria-label="Question text">{{ questionText }}</td>
  </tr>
</template>

<script lang="ts">
import { mixins } from 'vue-class-component';
import { Component, Prop, Vue } from 'vue-property-decorator';
import { truncateWithDots } from '@/utils/TextTransformers';

import IconButton from '@/components/IconButton.vue';
import MutationTypes from '@/state/MutationTypes';
import Question from '@/models/Question';
import StoreMixin from '@/mixins/StoreMixin';

@Component({
  components: {
    IconButton,
  },
})
export default class QuestionListRecord extends mixins(StoreMixin) {
  @Prop() public index!: number;
  @Prop() public question!: Question;

  private get questionText(): string {
    return truncateWithDots(this.question.question, 60);
  }

  private removeFromQuestionList(question: Question): void {
    this.store.commit(MutationTypes.QuestionList.removeFromList, question);
  }
}
</script>

<style scoped>
</style>

// Angular/src/app/components/question-list/question-list-record/question-list-record.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Store } from '@ngrx/store';
import { AppState } from '../../../state/app-state';
import { Question } from '../../../models/question';
import { truncateWithDots } from '../../../utils/text-transformers';
import { removeFromQuestionList } from '../../../state/app.actions';
import { IconButtonComponent } from '../../icon-button/icon-button';

@Component({
  selector: 'tr[app-question-list-record]',
  imports: [CommonModule, IconButtonComponent],
  templateUrl: './question-list-record.html',
  styleUrl: './question-list-record.css',
})
export class QuestionListRecord {
  @Input({ required: true }) index!: number;
  @Input({ required: true }) question!: Question;

  constructor(private store: Store<{ app: AppState }>) {}

  get questionText(): string {
    return truncateWithDots(this.question.question, 60);
  }

  removeFromQuestionList(question: Question): void {
    this.store.dispatch(removeFromQuestionList({ question }));
  }
}
