// Angular/src/app/components/question-list/question-trainer/question-trainer.ts
import { Component, DestroyRef, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Store } from '@ngrx/store';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { CKEditorModule } from '@ckeditor/ckeditor5-angular';
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import { AppState } from '../../../state/app-state';
import { Question } from '../../../models/question';
import { QuestionTestStatistics } from '../../../types/question-test-statistics';
import { getRandomInt } from '../../../utils/math';
import { IconButtonComponent } from '../../icon-button/icon-button';
import { addToQuestionList, removeFromQuestionList, setCurrentQuestion, setStatistics, toggleRepeat } from '../../../state/app.actions';
import { selectCurrentQuestion, selectQuestionList, selectQuestionStatistics, selectRepeatWrongQuestions } from '../../../state/app.selectors';

@Component({
  selector: 'app-question-trainer',
  imports: [CommonModule, FormsModule, CKEditorModule, IconButtonComponent],
  templateUrl: './question-trainer.html',
  styleUrl: './question-trainer.css',
})
export class QuestionTrainer implements OnInit {
  private readonly store = inject<Store<{ app: AppState }>>(Store);
  private readonly destroyRef = inject(DestroyRef);
  answerGiven = '';
  editor = ClassicEditor;
  editorConfig: any = {
    removePlugins: ['EasyImage', 'Heading', 'ImageCaption', 'ImageUpload', 'ImageToolbar', 'MediaEmbed'],
    toolbar: ['bold', 'italic', 'link', 'bulletedList', 'numberedList', 'blockQuote', 'insertTable', 'undo', 'redo']
  };
  showAnswer = false;

  private currentQuestion?: Question;
  private questionList: Question[] = [];
  private repeatWrongQuestions = true;
  private statistics = new QuestionTestStatistics();



  ngOnInit(): void {
    this.store
      .select(selectCurrentQuestion)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((question) => (this.currentQuestion = question));
    this.store
      .select(selectQuestionList)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((list) => (this.questionList = list));
    this.store
      .select(selectRepeatWrongQuestions)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((repeat) => (this.repeatWrongQuestions = repeat));
    this.store
      .select(selectQuestionStatistics)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((stats) => (this.statistics = stats));
  }

  get answerHtml(): string {
    if (!this.currentQuestion) {
      return '';
    }
    return this.currentQuestion.answer;
  }

  get canStart(): boolean {
    return this.questionList.length > 0 && !this.hasQuestion;
  }

  get hasQuestion(): boolean {
    return this.currentQuestion !== undefined;
  }

  get hasQuestionsInList(): boolean {
    return this.questionList.length > 0;
  }

  get questionHtml(): string {
    if (!this.currentQuestion) {
      return '';
    }
    return this.currentQuestion.question;
  }

  get repeat(): boolean {
    return this.repeatWrongQuestions;
  }

  get showStatistics(): boolean {
    return this.statistics.wrongCount > 0 || this.statistics.correctCount > 0;
  }

  get statisticsView(): QuestionTestStatistics {
    return this.statistics;
  }

  answerIsCorrect(): void {
    this.answerGiven = '';
    this.incrementCorrectCount();
    this.setNextQuestion();
  }

  answerIsWrong(): void {
    this.answerGiven = '';
    this.incrementWrongCount();
    if (this.repeat && this.currentQuestion) {
      this.store.dispatch(addToQuestionList({ question: this.currentQuestion }));
    }
    this.setNextQuestion();
  }

  start(): void {
    this.resetCount();
    this.setNextQuestion();
  }

  setNextQuestion(): void {
    this.showAnswer = false;
    const question = this.takeQuestion();
    this.store.dispatch(setCurrentQuestion({ question }));
    if (question) {
      this.store.dispatch(removeFromQuestionList({ question }));
    }
  }

  toggleRepeat(): void {
    this.store.dispatch(toggleRepeat());
  }

  incrementCorrectCount(): void {
    const correctCount = this.statistics.correctCount + 1;
    this.store.dispatch(setStatistics({ statistics: { correctCount } }));
  }

  incrementWrongCount(): void {
    const wrongCount = this.statistics.wrongCount + 1;
    this.store.dispatch(setStatistics({ statistics: { wrongCount } }));
  }

  resetCount(): void {
    this.store.dispatch(setStatistics({ statistics: { correctCount: 0, wrongCount: 0 } }));
  }

  takeQuestion(): Question | undefined {
    if (this.questionList.length === 0) {
      return undefined;
    }
    const questionIndex = getRandomInt(0, this.questionList.length - 1);
    return this.questionList[questionIndex];
  }
}

// src/components/questionList/QuestionTrainer.vue
<template>
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-2 text-left">
          <IconButton
            icon="redo-alt"
            @click="toggleRepeat"
            argument
            :color="repeat ? '#000000' : '#CCCCCC'"
            label="Toggle mode to repeat questions you answered incorrectly."
            size="m"
          />
        </div>
        <div class="col-8 text-center h5">Question trainer</div>
        <div class="col-2 text-right">
          <button
            aria-label="Start training"
            :class="['btn', {'btn-primary': canStart, 'btn-secondary': !canStart}]"
            @click="start"
            :disabled="!canStart"
          >Start</button>
        </div>
      </div>
    </div>
    <div class="card-body text-left">
      <div v-if="!hasQuestion && !hasQuestionsInList" class="text-center">
        <p v-show="showStatistics" aria-label="Recent statistics">
          You finished last training with
          <span class="stats-wrong-count">{{ statistics.wrongCount }}</span> question(s) answered incorrectly and
          <span
            class="stats-correct-count"
          >{{ statistics.correctCount }}</span> correctly.
        </p>
        <span
          aria-label="Instructions to create list"
        >Put together a list of questions below and then start training.</span>
      </div>
      <div
        v-else-if="!hasQuestion && hasQuestionsInList"
        class="text-center"
      >Press Start to begin training!</div>
      <div v-else>
        <div class="font-weight-bold">Question:</div>
        <div v-html="questionHtml" aria-label="Question html"></div>
        <div class="font-weight-bold answer">Your answer:</div>
        <div v-show="!showAnswer && hasQuestion">
          <ckeditor
            :editor="editor"
            v-model="answerGiven"
            :config="editorConfig"
            :disabled="!hasQuestion"
          ></ckeditor>
        </div>
        <div v-show="showAnswer" v-html="answerGiven"></div>
        <div class="font-weight-bold answer">Expected answer:</div>
        <div
          class="show-answer-banner"
          v-show="!showAnswer && hasQuestion"
          @click="showAnswer = true"
        >Click here to show the answer</div>
        <div aria-label="Answer html" v-show="showAnswer" v-html="answerHtml"></div>
      </div>
    </div>
    <div class="card-footer">
      <div class="row">
        <div class="col-2 text-left">
          <button
            aria-label="Wrong answer"
            class="btn btn-danger"
            :disabled="!hasQuestion || !showAnswer"
            @click="answerIsWrong"
          >
            Wrong
            <span v-show="hasQuestion">({{ statistics.wrongCount }})</span>
          </button>
        </div>
        <div class="col-8"></div>
        <div class="col-2 text-right">
          <button
            aria-label="Correct answer"
            class="btn btn-success"
            :disabled="!hasQuestion || !showAnswer"
            @click="answerIsCorrect"
          >
            Correct
            <span v-show="hasQuestion">({{ statistics.correctCount }})</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';
import { getRandomInt } from '@/utils/Math';
import { mixins } from 'vue-class-component';

// @ts-ignore
import CKEditor from '@ckeditor/ckeditor5-vue';
// @ts-ignore
import ClassicEditor from '@ckeditor/ckeditor5-build-classic';
import IconButton from '@/components/IconButton.vue';
import MutationTypes from '@/state/MutationTypes';
import StoreMixin from '@/mixins/StoreMixin';
import Question from '@/models/Question';
import QuestionTestStatistics from '@/types/QuestionTestStatistics';

@Component({
  components: {
    CKEditor,
    IconButton,
  },
})
export default class extends mixins(StoreMixin) {
  private answerGiven: string = '';
  private editor: any = ClassicEditor;
  private editorConfig: any = {
    removePlugins: [
      'EasyImage',
      'Heading',
      'ImageCaption',
      'ImageUpload',
      'ImageToolbar',
      'MediaEmbed',
    ],
    toolbar: [
      // 'heading',
      'bold',
      'italic',
      'link',
      'bulletedList',
      'numberedList',
      // 'imageUpload',
      'blockQuote',
      'insertTable',
      // 'mediaEmbed',
      'undo',
      'redo',
    ],
  };
  private showAnswer: boolean = false;

  private get answerHtml(): string {
    if (this.question === undefined) { return ''; }
    return this.question.answer;
  }

  private get canStart(): boolean {
    return this.store.state.questionList.length > 0 && !this.hasQuestion;
  }

  private get hasQuestion(): boolean {
    return this.question !== undefined;
  }

  private get hasQuestionsInList(): boolean {
    return this.store.state.questionList.length > 0;
  }

  private get question(): Question | undefined {
    return this.store.state.currentQuestion;
  }

  private get questionHtml(): string {
    if (this.question === undefined) { return ''; }
    return this.question.question;
  }

  private get repeat(): boolean {
    return this.store.state.repeatWrongQuestions;
  }

  private get showStatistics(): boolean {
    return (this.statistics.wrongCount > 0 || this.statistics.correctCount > 0);
  }

  private get statistics(): QuestionTestStatistics {
    return this.store.state.questionTestStatistics;
  }

  private answerIsCorrect(): void {
    this.answerGiven = '';
    this.incrementCorrectCount();
    this.setNextQuestion();
  }

  private answerIsWrong(): void {
    this.answerGiven = '';
    this.incrementWrongCount();
    this.store.commit(MutationTypes.QuestionList.addToList, this.question);
    this.setNextQuestion();
  }

  private start(): void {
    this.resetCount();
    this.setNextQuestion();
  }

  private setNextQuestion(): void {
    this.showAnswer = false;
    const question = this.takeQuestion();
    this.store.commit(MutationTypes.QuestionTrainer.setCurrentQuestion, question);
    if (question !== undefined) {
      this.store.commit(MutationTypes.QuestionList.removeFromList, question);
    }
  }

  private toggleRepeat(): void {
    this.store.commit(MutationTypes.QuestionTrainer.toggleRepeat);
  }

  private incrementCorrectCount(): void {
    const correctCount = this.store.state.questionTestStatistics.correctCount + 1;
    this.store.commit(MutationTypes.QuestionTrainer.setStatistics, { correctCount });
  }

  private incrementWrongCount(): void {
    const wrongCount = this.store.state.questionTestStatistics.wrongCount + 1;
    this.store.commit(MutationTypes.QuestionTrainer.setStatistics, { wrongCount });
  }

  private resetCount(): void {
    this.store.commit(MutationTypes.QuestionTrainer.setStatistics, {
      correctCount: 0,
      wrongCount: 0,
    });
  }

  private takeQuestion(): Question | undefined {
    if (this.store.state.questionList.length === 0) { return undefined; }
    const questionIndex = getRandomInt(0, this.store.state.questionList.length - 1);
    const question = this.store.state.questionList[questionIndex];
    return question;
  }
}
</script>

<style scoped>
.answer {
  margin-top: 10px;
}

.correct-wrong-buttons {
  margin-top: 10px;
}

.show-answer-banner {
  cursor: pointer;
}

.stats-wrong-count {
  color: red;
  font-weight: bold;
}

.stats-correct-count {
  color: green;
  font-weight: bold;
}
</style>
